services:
    ##################################################
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        depends_on: 
            - sio_db
    ##################################################
    sio_db:
        image: mysql:8.0
        container_name: sio_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_USER: user
            MYSQL_DATABASE: sio_db
        volumes:
            - ./var/database_volume:/var/lib/mysql
